server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://localhost:5432/therapy_db"
    username: postgres
    password: postgres
  jpa:
    database: postgresql
    properties:
      hibernate:
        hbm2ddl:
          auto: update

jwt:
  secret: secret-key
  lifetime: 60m

api:
  uri: /api/v1
  cors:
    allowed-origins: http://localhost:8080,http://localhost:5173,http://localhost:5174
      
